disabled = false
languageCode = "zh"
languageName = "Chinese"
weight = 1
title = "Ceresia Vision"

[params]
  displayName = "中文"
  isoCode = "zh"
  rtl = false
  dateFormat = "2006年1月2日"
  description = "计算机视觉"

[params.author]
  name = "ceresia.vision"
  email = "info@ceresia.vision"
  image = "img/logo.png"
  imageQuality = 96
  headline = "以全新视角分析您的产品"
  bio = "先进的农业计算机视觉"
