disabled = false
languageCode = "fr"
languageName = "French"
weight = 1
title = "Ceresia Vision"

[params]
  displayName = "FR"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Vision par ordinateur"

[params.author]
  name = "ceresia.vision"
  email = "info@ceresia.vision"
  image = "img/logo.png"
  imageQuality = 96
  headline = "Analyse ton produit avec d'autres yeux"
  bio = "Un peu sur vous"
