# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.


[[main]]
  name = "Cómo funciona?"
  pageRef = "como-funciona"
  weight = 5

[[main]]
  name = "Indices Ceresia"
  pageRef = "indices-ceresia"
  weight = 6

[[main]]
  name = "Quieres Somos"
  pageRef = "quienes-somos"
  weight = 20

[[main]]
  name = "Aplicaciones"
  weight = 10

[[main]]
  name = "Ceres Uva"
  parent = "Aplicaciones"
  pageRef = "aplicaciones/ceres-uva"
  weight = 20

[[main]]
  name = "Ceres Tomate"
  parent = "Aplicaciones"
  pageRef = "aplicaciones/ceres-tomate"
  weight = 20

[[main]]
  name = "Ceres Oliva"
  parent = "Aplicaciones"
  pageRef = "aplicaciones/ceres-oliva"
  weight = 20


#[[main]]
#  name = "Fase Experimental"
#  parent = "Aplicaciones"
#  pageRef = "aplicaciones/prototipos"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

[[main]]
  name = "Contacto"
  pageRef = "contacto"
  weight = 30

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
