[[main]]
 name = "How it Works?"
 pageRef = "como-funciona"
 weight = 5

[[main]]
 name = "Ceresia Indexes"
 pageRef = "indices-ceresia"
 weight = 6

[[main]]
 name = "About Us"
 pageRef = "quienes-somos"
 weight = 20

[[main]]
 name = "Applications"
 weight = 10

[[main]]
 name = "Ceres Grape"
 parent = "Applications"
 pageRef = "aplicaciones/ceres-uva"
 weight = 20

[[main]]
 name = "Ceres Tomato"
 parent = "Applications"
 pageRef = "aplicaciones/ceres-tomate"
 weight = 20

[[main]]
 name = "Ceres Olive"
 parent = "Applications"
 pageRef = "aplicaciones/ceres-oliva"
 weight = 20



[[main]]
 name = "Contact"
 pageRef = "contacto"
 weight = 30




